[build]
  base = "frontend"
  command = "npm install && node node_modules/vite/bin/vite.js build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[build.processing.secrets]
  omit_keys = ["VITE_GOOGLE_CLIENT_ID"]