# Generated by Django 4.2.7 on 2026-05-06 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoastSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_type', models.CharField(choices=[('resume', 'Resume'), ('code', 'Code'), ('pitch_deck', 'Pitch Deck'), ('linkedin', 'LinkedIn Profile'), ('essay', 'Essay'), ('ui_design', 'UI Design')], max_length=20)),
                ('input_text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='roast_files/')),
                ('roast_output', models.TextField(blank=True, null=True)),
                ('fix_output', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('intensity', models.CharField(choices=[('gentle', 'Gentle'), ('honest', 'Honest'), ('gordon_ramsay', 'Gordon Ramsay'), ('simon_cowell', 'Simon Cowell')], default='honest', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
